%%{init: {"theme":"base","htmlLabels":false,"themeVariables":{"fontFamily":"Open Sans, Arial, sans-serif","primaryColor":"#9e1b32","primaryTextColor":"#ffffff","primaryBorderColor":"#9e1b32","lineColor":"#333e48","textColor":"#333e48"}}}%%
gitGraph
    commit id: "mmd"
    branch svg
    checkout svg
    commit id: "render"
    commit id: "fragment"
    checkout main
    merge svg
    commit id: "video"
