%%{init: {"theme":"base","htmlLabels":false,"themeVariables":{"fontFamily":"Open Sans, Arial, sans-serif","primaryColor":"#9e1b32","primaryTextColor":"#ffffff","primaryBorderColor":"#9e1b32","lineColor":"#333e48","textColor":"#333e48"}}}%%
venn-beta
    title "SVG and Video"
    set SVG["SVG"]:10
    set Video["Video"]:10
    union SVG,Video["Fragments"]:4
